package jass

const (
	/** Программа */
	Prog = "Prog"

	TypeDecl   = "TypeDecl"
	Glob       = "Glob"
	GConst     = "GConst"
	GVar       = "GVar"
	GArr       = "GArr"
	LVar       = "LVar"
	LArr       = "LArr"
	Expr       = "Expr"
	RVar       = "RVar"
	FCall      = "FCall"
	RArr       = "RArr"
	RFunc      = "RFunc"
	Native     = "Native"
	CNative    = "CNative"
	FuncDecl   = "FuncDecl"
	Params     = "Params"
	Func       = "Func"
	CFunc      = "CFunc"
	FuncLocals = "FuncLocals"
	FuncBody   = "FuncBody"
	Comm       = "Comm"
	Debug      = "Debug"
	Set        = "Set"
	ASet       = "ASet"
	If         = "If"
	Cond       = "Cond"
	Then       = "Then"
	ElseCond   = "ElseCond"
	Else       = "Else"
	Loop       = "Loop"
	Exit       = "Exit"
	Return     = "Return"

	TypeName = "TypeName"
	BaseType = "BaseType"
	Type     = "Type"
	Name     = "Name"
	Val      = "Val"
	Oper     = "Oper"
	Result   = "Result"
	Param    = "Param"
	Ind      = "Ind"
	Par      = "Par"

	YdweMacro = "YdweMacro"
)
